Class PlasmaBeamCount : Inventory 
{ 
	Default
	{
		Inventory.MaxAmount 20;
	}
}

Class PlasmaBeam : MDOBeam
{
	Default
	{
		Weapon.SelectionOrder 2000;
		Weapon.SlotNumber 3;
		Inventory.PickupMessage "Got the Plasma Beam!";
		Obituary "%k melted %o.";
		Inventory.Icon "WEAPPLBM";
	}

    States
    {
      Spawn:
        SOUL B -1;
        Stop;
		
	  Ready:
        MBEM A 0 ACS_ExecuteWithResult(476, 1);
		TNT1 A 0 A_SetCrosshair(11);
        Goto Ready2;
		
      Ready2:
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID A 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID A 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID B 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID B 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID E 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID E 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID F 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID F 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID C 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID C 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID D 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID D 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID E 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID E 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID F 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID F 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID G 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID G 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID C 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID D 1 A_WeaponReady;
		TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 0), "Missile");
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594, 28, 1), "SuperMissile");
		MBID C 1 A_WeaponReady;
        TNT1 A 0 A_JumpIfInventory("IsShinesparking",1,"ShineBright");
        TNT1 A 0 A_JumpIfInventory("SpeedBoosterActive",1,"D_RUNNIN");
        Goto Ready;

	  Select:
        TNT1 AAAAAAAAAAAAAAAAAAAA 0 A_Raise;
        MBEM A 1 A_Raise;
        Loop;

	  Deselect:
        MBEM A 0 ACS_ExecuteWithResult(476, 0);
        TNT1 A 0 A_StartSound("beam/deselect",5);
      Deselect2:
		MBEM RSTUVW 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        TNT1 A 0 A_JumpIfHealthLower(1, "DeadLower");
        MBEM A 5 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
        TNT1 AAAAAAAAAAAAAAAAAAAA 0 A_Lower;
        MBEM A 0 A_Lower;
        Loop;

      DeadLower:
        XBEM A 1 A_Lower;
        Loop;
		
	  Fire:
        MBEM A 0 ACS_ExecuteWithResult(476, 0);
        TNT1 A 0 A_JumpIfInventory("IceBeamChilled",1,"FireChilled");
        TNT1 A 0 A_StartSound("plbeam/fire");
        TNT1 A 0 A_Recoil(0.05);
        TNT1 A 0 A_JumpIfInventory("CoopModeOn",1,"FireCoop");
        TNT1 A 0 A_FireProjectile("PlasmaBolt",0,0,12,-2,0,0);
        Goto FireFinish;

	  PreHold:
		TNT1 A 0;
		TNT1 A 0 A_Refire;
		Goto Ready;

	  FireCoop:
        TNT1 A 0 A_FireProjectile("PlasmaBolt",0,0,12,-2,0,0);
      FireFinish:
        TNT1 A 0 A_AlertMonsters;
        TNT1 A 0 A_Light2;
        MBEM B 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Light1;
        MBEM C 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Light0;
        MBEM D 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM EEFFFEEGHA 1 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM A 1 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM A 6 A_WeaponReady(WRF_NOSWITCH);
		TNT1 A 0 A_JumpIfInventory("ChargeBeamAcquired", 1, "PreHold");
        Goto Ready;

	  FireChilled:
        TNT1 A 0 A_StartSound("plbeam/fire", CHAN_WEAPON);
        TNT1 A 0 A_Recoil(0.05);
        TNT1 A 0 A_JumpIfInventory("CoopModeOn",1,"ChilledCoop");
        TNT1 A 0 A_FireProjectile("PlasmaBolt",0,0,12,-2,0,0);
        Goto ChilledFinish;
		
	  ChilledCoop:
        TNT1 A 0 A_FireProjectile("PlasmaBolt",0,0,12,-2,0,0);
      ChilledFinish:
        TNT1 A 0 A_AlertMonsters;
        TNT1 A 0 A_Light2;
        MBEM B 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Light1;
        MBEM C 2 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Light0;
        MBEM D 2 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM EEEFFFF 1 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM EEEGGHHA 1 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM A 6 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Refire;
        MBEM A 6 A_WeaponReady(WRF_NOSWITCH);
        Goto Ready;

	  Hold:
        TNT1 A 0 A_JumpIfInventory("PowerBeamCharged",1,"HoldFinal2");
        TNT1 A 0 A_JumpIfInventory("PowerBeamChargeLevel",25,"HoldFinal");
        TNT1 A 0 A_JumpIfInventory("PowerBeamChargeLevel",26,"Hold7");
        TNT1 A 0 A_JumpIfInventory("PowerBeamChargeLevel",21,"Hold6");
        TNT1 A 0 A_JumpIfInventory("PowerBeamChargeLevel",16,"Hold5");
        TNT1 A 0 A_JumpIfInventory("PowerBeamChargeLevel",11,"Hold4");
        TNT1 A 0 A_JumpIfInventory("PowerBeamChargeLevel",6,"Hold3");
        TNT1 A 0 A_JumpIfInventory("PowerBeamChargeLevel",1,"Hold2");
        TNT1 A 0 A_StartSound("pbeam/charge",5);
      Hold2:
        TNT1 A 0;
        TNT1 A 0 A_JumpIfInventory("PowerBeamChargeLevel",25,"HoldFinal");
        TNT1 A 0 A_GiveInventory("PowerBeamChargeLevel",1);
        MBEM KK 1 BRIGHT A_SpawnItemEx("PlasmaBeamCharging1",-15,64,(sin(pitch)*-63)+26,0,0,0,-270,32);
        TNT1 A 0 A_Refire;
      HoldFire:
        TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("PowerBeamHalfCharged",1,"HalfShotHoldFinish");
        TNT1 A 0 A_StartSound("silence",5);
        TNT1 A 0 A_TakeInventory("PowerBeamChargeLevel",25);
        TNT1 A 0 A_ClearRefire;
        TNT1 A 0 A_StartSound("plbeam/fire", CHAN_WEAPON);
        TNT1 A 0 A_Recoil(0.05);
        TNT1 A 0 A_JumpIfInventory("CoopModeOn",1,"UnholdCoop");
        TNT1 A 0 A_FireProjectile("PlasmaBolt",0,0,12,-2,0,0);
        Goto UnholdFinish;

	  UnholdCoop:
        TNT1 A 0 A_FireProjectile("PlasmaBolt",0,0,12,-2,0,0);
      UnholdFinish:
        TNT1 A 0 A_AlertMonsters;
        TNT1 A 0 A_Light2;
        MBEM B 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Light1;
        MBEM C 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Light0;
        MBEM D 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM EEFFF 1 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM EEGHA 1 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM A 6 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Refire;
        MBEM A 6 A_WeaponReady(WRF_NOSWITCH);
        Goto Ready;

	  Hold3:
        TNT1 A 0;
        TNT1 A 0 A_JumpIfInventory("PowerBeamChargeLevel",25,"HoldFinal");
        TNT1 A 0 A_GiveInventory("PowerBeamChargeLevel",1);
        MBEM LL 1 BRIGHT A_SpawnItemEx("PlasmaBeamCharging2",-15,64,(sin(pitch)*-63)+26,0,0,0,-270,32);
        TNT1 A 0 A_Refire;
        Goto HoldFire;
		
	  Hold4:
        TNT1 A 0;
        TNT1 A 0 A_JumpIfInventory("PowerBeamChargeLevel",25,"HoldFinal");
        TNT1 A 0 A_GiveInventory("PowerBeamChargeLevel",1);
		TNT1 A 0 A_GiveInventory("PowerBeamHalfCharged",1);
        MBEM MM 1 BRIGHT A_SpawnItemEx("PlasmaBeamCharging3",-15,64,(sin(pitch)*-63)+26,0,0,0,-270,32);
        TNT1 A 0 A_Refire;
        Goto HoldFire;

	  Hold5:
        TNT1 A 0;
        TNT1 A 0 A_JumpIfInventory("PowerBeamChargeLevel",25,"HoldFinal");
        TNT1 A 0 A_GiveInventory("PowerBeamChargeLevel",1);
        MBEM NN 1 BRIGHT A_SpawnItemEx("PlasmaBeamCharging4",-15,64,(sin(pitch)*-63)+26,0,0,0,-270,32);
        TNT1 A 0 A_Refire;
        Goto HoldFire;

	  Hold6:
        TNT1 A 0;
        TNT1 A 0 A_JumpIfInventory("PowerBeamChargeLevel",25,"HoldFinal");
        TNT1 A 0 A_GiveInventory("PowerBeamChargeLevel",1);
        MBEM OO 1 BRIGHT A_SpawnItemEx("PlasmaBeamCharging5",-15,64,(sin(pitch)*-63)+26,0,0,0,-270,32);
        TNT1 A 0 A_Refire;
        Goto HoldFire;

	  Hold7:
        TNT1 A 0;
        TNT1 A 0 A_JumpIfInventory("PowerBeamChargeLevel",25,"HoldFinal");
        TNT1 A 0 A_GiveInventory("PowerBeamChargeLevel",1);
        MBEM PP 1 BRIGHT A_SpawnItemEx("PlasmaBeamCharging6",-15,64,(sin(pitch)*-63)+26,0,0,0,-270,32);
        TNT1 A 0 A_Refire;
        Goto HoldFire;

	  HoldFinal:
        TNT1 A 0;
        TNT1 A 0 A_GiveInventory("PowerBeamCharged",1);
        TNT1 A 0 A_StartSound("pbeam/idle",7);
      HoldFinal2:
        TNT1 A 0;
        TNT1 A 0 A_JumpIfInventory("SpeedBoosterActive",1,"D_RUNNIN");
        TNT1 A 0 A_JumpIfInventory("PowerBeamIdle",26,"HoldFinal3");
        TNT1 A 0 A_GiveInventory("PowerBeamIdle",1);
        MBEM QQ 1 BRIGHT A_SpawnItemEx("PlasmaBeamCharging7",-15,64,(sin(pitch)*-63)+26,0,0,0,-270,32);//A_FireCustomMissile("PlasmaBeamChargingSpawner7",0,0,0,0,0,0);
        TNT1 A 0 A_JumpIfInventory("SFSynthFireRight",1,"ChargeCombo");
		TNT1 A 0 TheSucc();
        TNT1 A 0 A_Refire;
      HoldFinish:
        TNT1 A 0 A_StartSound("silence",7);//A_StopSoundEx("soundslot7");
        TNT1 A 0 A_StartSound("plbeam/chfire", CHAN_WEAPON);
        TNT1 A 0 A_TakeInventory("PowerBeamCharged",1);
        TNT1 A 0 A_TakeInventory("PowerBeamChargeLevel",25);
        TNT1 A 0 A_TakeInventory("PowerBeamIdle",34);
		TNT1 A 0 A_TakeInventory("PowerBeamHalfCharged",1);
        TNT1 A 0 A_ClearRefire;
        TNT1 A 0 A_Recoil(2);
        TNT1 A 0 A_ZoomFactor(0.95,ZOOM_INSTANT);
        TNT1 A 0 Radius_Quake(4,8,0,1,0);
        TNT1 A 0 A_JumpIfInventory("CoopModeOn",1,"ChargedCoop");
        TNT1 A 0 A_FireProjectile("PlasmaBoltCharged",1,0,12,-2,0,0);
        Goto ChargedFinish;
		
	  HalfShotHoldFinish:
        TNT1 A 0 A_StopSound(5);
        TNT1 A 0 A_StartSound("plbeam/fire", CHAN_WEAPON);
        TNT1 A 0 A_TakeInventory("PowerBeamCharged",1);
        TNT1 A 0 A_TakeInventory("PowerBeamChargeLevel",25);
        TNT1 A 0 A_TakeInventory("PowerBeamIdle",34);
		TNT1 A 0 A_TakeInventory("PowerBeamHalfCharged",1);
        TNT1 A 0 A_ClearRefire;
        TNT1 A 0 A_Recoil(2);
        TNT1 A 0 A_ZoomFactor(0.95,ZOOM_INSTANT);
        TNT1 A 0 Radius_Quake(1,8,0,1,0);
		TNT1 A 0 A_FireProjectile("PlasmaBoltHalfCharged",1,0,12,-2,0,0);
        Goto ChargedFinish;

	  ChargedCoop:
        TNT1 A 0 A_FireProjectile("PlasmaBoltChargedCoop",0,0,12,-2,0,0);
      ChargedFinish:
        TNT1 A 0 A_AlertMonsters;
        TNT1 A 0 A_Light2;
        MBEM B 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Light1;
        TNT1 A 0 A_ZoomFactor(0.975,ZOOM_INSTANT);
        MBEM C 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Light0;
        TNT1 A 0 A_ZoomFactor(1.00,ZOOM_INSTANT);
        MBEM D 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM EEFFFEEGHA 1 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM A 6 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        Goto Ready;

	  HoldFinal3:
        TNT1 A 0;
        TNT1 A 0 A_TakeInventory("PowerBeamIdle",99);
        TNT1 A 0 A_StartSound("pbeam/idle",7);
		TNT1 A 0 TheSucc();
        Goto HoldFinal2;

      Missile:
        TNT1 A 0 ACS_ExecuteWithResult(476, 0);
        TNT1 A 0 ACS_ExecuteWithResult(594, 29, 0, 1);
        TNT1 A 0 A_StartSound("missile/fire",CHAN_WEAPON);
        TNT1 A 0 A_AlertMonsters;

        TNT1 A 0 A_ZoomFactor(0.95,ZOOM_INSTANT);

        TNT1 A 0 A_Recoil(2);
        TNT1 A 0 Radius_Quake(1,8,0,1,0);

        TNT1 A 0 A_JumpIfInventory("CoopModeOn",1,"Missile_Coop");
        Goto Missile_DM;

      Missile_DM:
        TNT1 A 0 A_FireProjectile("PowerMissile",0,1,12,-2,0,0);
        Goto MissileAnim;

      Missile_Coop:
        TNT1 A 0 A_FireProjectile("PowerMissile",0,1,12,-2,0,0);
        Goto MissileAnim;

	  MissileAnim:
        MBEM A 0 A_JumpIfInventory("IceBeamChilled", 1, "MissileAnim_Chilled");
        MBEM A 0 A_Light2;
        MBEM I 1 BRIGHT A_WeaponReady(WRF_NOFIRE|WRF_NOSWITCH);
        MBEM A 0 A_Light1;
        MBEM A 0 A_ZoomFactor(0.975,ZOOM_INSTANT);
        MBEM J 1 BRIGHT A_WeaponReady(WRF_NOFIRE|WRF_NOSWITCH);
        MBEM A 0 A_Light0;
        MBEM A 0 A_ZoomFactor(1.00,ZOOM_INSTANT);
        MBEM E 1 A_WeaponReady(WRF_NOFIRE|WRF_NOSWITCH);
        MBEM EEFFFEEGGHH 1 A_WeaponReady(WRF_NOFIRE|WRF_NOSWITCH);
        MBEM A 2 A_WeaponReady(WRF_NOFIRE|WRF_NOSWITCH);
        Goto Ready;

	  MissileAnim_Chilled:
        TNT1 A 0 A_Light2;
        MBEM I 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Light1;
        TNT1 A 0 A_ZoomFactor(0.975,ZOOM_INSTANT);
        MBEM J 2 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Light0;
        TNT1 A 0 A_ZoomFactor(1.00,ZOOM_INSTANT);
        MBEM E 1 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM EEEFFFFEEEGGGHHHAAA 1 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM A 2 A_WeaponReady(WRF_NOSECONDARY|WRF_NOSWITCH);
        Goto Ready;

      SuperMissile:
        TNT1 A 0 ACS_ExecuteWithResult(476, 0);
        TNT1 A 0 ACS_ExecuteWithResult(594, 29, 1, 1);
        TNT1 A 0 A_StartSound("supermissile/fire", CHAN_WEAPON);
        TNT1 A 0 A_AlertMonsters;

        TNT1 A 0 A_ZoomFactor(0.925,ZOOM_INSTANT);

        TNT1 A 0 A_Recoil(5);
        TNT1 A 0 Radius_Quake(2,8,0,1,0);

        TNT1 A 0 A_JumpIfInventory("CoopModeOn",1,"SuperCoop");
        Goto SuperDM;

      SuperDM:
        TNT1 A 0 A_FireProjectile("SuperMissile",0,0,12,-2,0,0);
        Goto SuperAnim;

      SuperCoop:
        TNT1 A 0 A_FireProjectile("SuperMissile",0,0,12,-2,0,0);
        Goto SuperAnim;

	  SuperAnim:
        TNT1 A 0 A_SetAngle(angle+(random(-200,200)/100.00));
        TNT1 A 0 A_SetPitch(pitch-(random(300,500)/100.00));
        TNT1 A 0 A_AlertMonsters;
        TNT1 A 0 A_Light2;
        MBEM I 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Light1;
        TNT1 A 0 A_ZoomFactor(0.95,ZOOM_INSTANT);
        MBEM J 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Light0;
        TNT1 A 0 A_ZoomFactor(1.00,ZOOM_INSTANT);
        MBEM E 1 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM EEFFFEEGGHHAA 1 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM A 8 A_WeaponReady(WRF_NOSECONDARY|WRF_NOSWITCH);
        Goto Ready;

	  ChargeCombo:
		TNT1 A 0 A_JumpIfInventory("SolarFlareAcquired",1,1);
        TNT1 A 0 A_JumpIfInventory("MissileAmmo",10,1);
        Goto HoldFinal2;
        TNT1 A 0;
        MBEM R 20 BRIGHT A_StartSound("combo/ready",7);
        TNT1 A 0 A_StartSound("combo/plasma", CHAN_WEAPON);
        TNT1 A 0 A_TakeInventory("PowerBeamCharged",1);
        TNT1 A 0 A_TakeInventory("PowerBeamChargeLevel",25);
        TNT1 A 0 A_TakeInventory("PowerBeamIdle",34);
        TNT1 A 0 A_ClearRefire;
        TNT1 A 0 A_Recoil(10);
        TNT1 A 0 A_ZoomFactor(0.9,ZOOM_INSTANT);
        TNT1 A 0 Radius_Quake(2,8,0,1,0);
        TNT1 A 0 A_JumpIfInventory("CoopModeOn",1,"ComboCoop");
        TNT1 A 0 A_FireProjectile("PlasmaComboMissile",0,0,12,-2,0,0);
        Goto ComboFinish;

	  ComboCoop:
        TNT1 A 0 A_FireProjectile("PlasmaComboMissileCoop",0,0,12,-2,0,0);
      ComboFinish:
        TNT1 A 0 A_TakeInventory("MissileAmmo",10);
        TNT1 A 0 A_SetAngle(angle+(random(-200,200)/100.00));
        TNT1 A 0 A_SetPitch(pitch-(random(300,500)/100.00));
        TNT1 A 0 A_AlertMonsters;
        TNT1 A 0 A_Light2;
        MBEM I 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Light1;
        TNT1 A 0 A_ZoomFactor(0.975,ZOOM_INSTANT);
        MBEM J 1 BRIGHT A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        TNT1 A 0 A_Light0;
        TNT1 A 0 A_ZoomFactor(1.00,ZOOM_INSTANT);
        MBEM E 1 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM EEFFFEEGGHHAA 1 A_WeaponReady(WRF_NOSECONDARY|WRF_NOPRIMARY|WRF_NOSWITCH);
        MBEM A 8 A_WeaponReady(WRF_NOSECONDARY|WRF_NOSWITCH);
        Goto Ready;

	  D_RUNNIN:
		MBEM A 0 ACS_ExecuteWithResult(476, 0);
        TNT1 A 0 A_TakeInventory("PowerBeamCharged",1);
        TNT1 A 0 A_TakeInventory("PowerBeamChargeLevel",25);
        TNT1 A 0 A_TakeInventory("PowerBeamIdle",34);
        TNT1 A 0 A_TakeInventory("MissileCharged",1);
        TNT1 A 0 A_TakeInventory("MissileChargeLevel",34);
        TNT1 A 0 A_ClearRefire;
        TNT1 A 0 Offset(0,32);
        MBEM A 1 Offset(0,40);
        MBEM A 1 Offset(0,50);
        MBEM A 1 Offset(0,60);
        MBEM A 1 Offset(0,70);
        MBEM A 1 Offset(0,80);
        MBEM A 1 Offset(0,90);
        MBEM A 1 Offset(0,100);
        MBEM A 1 Offset(0,110);
        MBEM A 1 Offset(0,120);
        MBEM A 1 Offset(0,130);
        MBEM A 1 Offset(0,140);
      IdleLoop:
        TNT1 A 1;
		TNT1 A 0 A_JumpIfInventory("ShinesparkCharge",1,"PreShine");
        TNT1 A 0 A_JumpIfInventory("SpeedBoosterActive",1,"IdleLoop");
        Goto BackToNormal;
		
	  PreShine:
		TNT1 A 1;
		TNT1 A 0 A_JumpIfInventory("ShinesparkCharge",1,"PreShine");
		Goto Ready;
		
	  ShineBright:
		TNT1 A 0 Offset(0,32);
        MBEM A 1 Offset(0,40);
        MBEM A 1 Offset(0,50);
        MBEM A 1 Offset(0,60);
        MBEM A 1 Offset(0,70);
        MBEM A 1 Offset(0,80);
        MBEM A 1 Offset(0,90);
        MBEM A 1 Offset(0,100);
        MBEM A 1 Offset(0,110);
        MBEM A 1 Offset(0,120);
        MBEM A 1 Offset(0,130);
        MBEM A 1 Offset(0,140);
	  ShineLoop:
        TNT1 A 1;
		TNT1 A 0 A_JumpIfInventory("IsShinesparking",1,"ShineLoop");
		Goto BackToNormal;

      BackToNormal:
		MBEM A 1 Offset(0,140);
        MBEM A 1 Offset(0,130);
        MBEM A 1 Offset(0,120);
        MBEM A 1 Offset(0,110);
        MBEM A 1 Offset(0,100);
        MBEM A 1 Offset(0,90);
        MBEM A 1 Offset(0,80);
        MBEM A 1 Offset(0,70);
        MBEM A 1 Offset(0,60);
        MBEM A 1 Offset(0,50);
        MBEM A 1 Offset(0,40);
        TNT1 A 0 Offset(0,32);
        Goto Ready;
    }
}

Class PlasmaBolt : Actor
{
	Default
	{
		Radius 8;
		Height 8;
		Projectile;
		+NOGRAVITY;
		+RIPPER;
		+ROCKETTRAIL;
		+FORCEXYBILLBOARD;
		Speed 55;
		Damage (8);
		Scale 0.01;
		RenderStyle "Add";
		Alpha 0.95;
		DeathSound "plbeam/hit";
		Damagetype "PlasmaBeam";
		Decal "DoomImpScorch";
	}
	
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS A 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS B 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS C 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS D 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS E 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS F 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS G 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS H 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS I 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS G 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS H 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS I 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS G 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS H 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMS I 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160);
        //TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        //TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        //TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        //LSMS J 1 BRIGHT A_SpawnItemEx("PlasmaTrail",0,0,0,0,0,0,0,160)
        Stop;

      Death:
        TNT1 A 0;
        TNT1 A 0 A_Stop;
        TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 AAAAAAAAAAAAA 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",12,"Death12");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",11,"Death11");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",10,"Death10");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",9,"Death9");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",8,"Death8");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",7,"Death7");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",6,"Death6");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",5,"Death5");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",4,"Death4");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",3,"Death3");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",2,"Death2");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",1,"Death1");

      Death1:
        LSMS A 1 BRIGHT;

      Death2:
        LSMS B 1 BRIGHT;

      Death3:
        LSMS C 1 BRIGHT;

      Death4:
        LSMS D 1 BRIGHT;

      Death5:
        LSMS E 1 BRIGHT;

      Death6:
        LSMS F 1 BRIGHT;

      Death7:
        LSMS G 1 BRIGHT;

      Death8:
        LSMS H 1 BRIGHT;

      Death9:
        LSMS I 1 BRIGHT;

      Death10:
        LSMS J 1 BRIGHT;

      Death11:
        LSMS K 1 BRIGHT;

      Death12:
        LSMS L 1 BRIGHT;
        Stop;
    }
}

Class PlasmaBoltCoop : PlasmaBolt 
{ 
	Default
	{
		Damage (12);
		Speed 45;
		Scale 0.2;
	}
}

Class PlasmaTrail : Actor
{
	Default
	{
		Alpha 0.55;
		Scale 0.2;
		+NOINTERACTION;
		+CLIENTSIDEONLY;
		+FORCEXYBILLBOARD;
		RenderStyle "Add";
	}
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594,0,0,0) == 1,"Nope");
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        LSMT ABCDEFGHIJKL 1 BRIGHT A_SpawnItemEx("PlasmaTrailFlicker",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,200)/100.00,random(-180,180),160,0);
		Stop;

      Nope:
        TNT1 A 1;
        Stop;
    }
}

Class PlasmaTrailFlicker : PlasmaTrail
{
	Default
	{
		+FORCEXYBILLBOARD;
		Scale 0.04;
	}

    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594,0,0,0) == 1,"Nope");
        LSMT ABCDEFGHIJKL 1 BRIGHT;
        Stop;

      Nope:
        TNT1 A 1;
        Stop;
    }
}

Class PlasmaSmoke : Actor
{
	Default
	{
		Speed 1;
		Scale 0.08;
		Alpha 0.4;
		RenderStyle "Add";
		+NOGRAVITY;
		+NOBLOCKMAP;
		+FLOORCLIP;
		-SOLID;
		+EXPLODEONWATER;
		-CANBOUNCEWATER;
		+DONTSPLASH;
		+NOTELEPORT;
		+CLIENTSIDEONLY;
		+FORCEXYBILLBOARD;
	}
	
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594,0,0,0) == 1,"Nope");
        MISL BC 1 BRIGHT;
        TNT1 A 0 A_Jump(256,"Spawn1","Spawn2","Spawn3","Spawn4");
        TNT1 A 1;
        Stop;

      Spawn1:
        SMK1 ABCDEFGHIJKLMNOPQR 1;
        Stop;

      Spawn2:
        SMK2 ABCDEFGHIJKLMNOPQR 1;
        Stop;

      Spawn3:
        SMK3 ABCDEFGHIJKLMNOP 1;
        Stop;

      Spawn4:
        SMK4 ABCDEFGHIJKLMNOP 1;
        Stop;

      Nope:
        TNT1 A 1;
        Stop;
    }
}

Class PlasmaSpark : Actor
{
	Default
	{
		Radius 1;
		Scale 0.05;
		Gravity 0.1;
		Speed 2;
		RenderStyle "Add";
		Projectile;
		+CLIENTSIDEONLY;
		+RANDOMIZE;
		+NOTELEPORT;
		+EXPLODEONWATER;
		-CANBOUNCEWATER;
		+DONTSPLASH;
		+THRUACTORS;
		-NOGRAVITY;
		+NOINTERACTION;
		+DOOMBOUNCE;
		+FORCEXYBILLBOARD;
	}
	
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594,0,0,0) == 1,"Nope");
        TNT1 A 0 A_Jump(64,7);
        TNT1 A 0 A_Jump(64,5);
        TNT1 A 0 A_Jump(64,3);
        TNT1 A 0 A_Jump(64,1);
        PLSS ABCDE 2 BRIGHT A_FadeOut(0.015);
        loop;

      Nope:
        TNT1 A 1;
        Stop;
    }
}

Class PlasmaBeamChargingSpawner1 : Actor
{
	Default
	{
		-SOLID;
		+NOINTERACTION;
		+CLIENTSIDEONLY;
		+NOTIMEFREEZE;
		Radius 0;
		Height 0;
		Speed 24;
	}
	
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 1;
        TNT1 A 0 A_SpawnItemEx("PlasmaBeamCharging1",-14,0,-3,0,0,0,-270,32);
        Stop;
    }
}

Class PlasmaBeamChargingSpawner2 : PlasmaBeamChargingSpawner1
{
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 1;
        TNT1 A 0 A_SpawnItemEx("PlasmaBeamCharging2",-14,0,-3,0,0,0,-270,32);
        Stop;
    }
}

Class PlasmaBeamChargingSpawner3 : PlasmaBeamChargingSpawner1
{
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 1;
        TNT1 A 0 A_SpawnItemEx("PlasmaBeamCharging3",-14,0,-3,0,0,0,-270,32);
        Stop;
    }
}

Class PlasmaBeamChargingSpawner4 : PlasmaBeamChargingSpawner1
{
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 1;
        TNT1 A 0 A_SpawnItemEx("PlasmaBeamCharging4",-14,0,-3,0,0,0,-270,32);
        Stop;
    }
}

Class PlasmaBeamChargingSpawner5 : PlasmaBeamChargingSpawner1
{
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 1;
        TNT1 A 0 A_SpawnItemEx("PlasmaBeamCharging5",-14,0,-3,0,0,0,-270,32);
        Stop;
    }
}

Class PlasmaBeamChargingSpawner6 : PlasmaBeamChargingSpawner1
{
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 1;
        TNT1 A 0 A_SpawnItemEx("PlasmaBeamCharging6",-14,0,-3,0,0,0,-270,32);
        Stop;
    }
}

Class PlasmaBeamChargingSpawner7 : PlasmaBeamChargingSpawner1
{
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 1;
        TNT1 A 0 A_SpawnItemEx("PlasmaBeamCharging7",-14,0,-3,0,0,0,-270,32);
        Stop;
    }
}

Class PlasmaBeamCharging1 : Actor
{
	Default
	{
		RenderStyle "Add";
		Alpha 0.75;
		Scale 0.07;
		+CLIENTSIDEONLY;
		+NOINTERACTION;
		+NOTIMEFREEZE;
		+FORCEXYBILLBOARD;
	}
	
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594,0,0,0) == 1,"Simple");
        TNT1 A 0 A_Jump(256,"Spawn1","Spawn2","Spawn3","Spawn4");
        TNT1 A 1;
        Loop;

      Spawn1:
        MBCH ABCDA 1 bright A_FadeOut(0.15);
        Stop;

      Spawn2:
        MBCH BCDAB 1 bright A_FadeOut(0.15);
        Stop;

      Spawn3:
        MBCH CDABC 1 bright A_FadeOut(0.15);
        Stop;

      Spawn4:
        MBCH DABCD 1 bright A_FadeOut(0.15);
        Stop;

      Simple:
        TNT1 A 0;
        TNT1 A 0 A_Jump(256,"Spawn1B","Spawn2B","Spawn3B","Spawn4B");
        TNT1 A 1;
        loop;

      Spawn1B:
        MBCH A 2 bright;
        Stop;

      Spawn2B:
        MBCH B 2 bright;
        Stop;

      Spawn3B:
        MBCH C 2 bright;
        Stop;

      Spawn4B:
        MBCH D 2 bright;
        Stop;
    }
}

Class PlasmaBeamCharging2 : PlasmaBeamCharging1 
{ 
	Default
	{
		Scale 0.08; 
	}
}

Class PlasmaBeamCharging3 : PlasmaBeamCharging1 
{ 
	Default
	{
		Scale 0.09;
	}
}

Class PlasmaBeamCharging4 : PlasmaBeamCharging1 
{ 
	Default
	{
		Scale 0.105; 
	}
}

Class PlasmaBeamCharging5 : PlasmaBeamCharging1 
{ 
	Default
	{
		Scale 0.12; 
	}
}

Class PlasmaBeamCharging6 : PlasmaBeamCharging1 
{
	Default
	{
		Scale 0.135; 
	}
}

Class PlasmaBeamCharging7 : PlasmaBeamCharging1
{
	Default
	{
		Scale 0.15; 
	}
}

Class PlasmaBoltCharged : Actor
{
	Default
	{
		Radius 12;
		Height 10;
		Projectile;
		+NOGRAVITY;
		+RIPPER;
		+ROCKETTRAIL;
		+FORCEXYBILLBOARD;
		Speed 60;
		Damage (30);
		Scale 0.3;
		RenderStyle "Add";
		Alpha 0.75;
		DeathSound "plbeam/chit";
		Damagetype "PlasmaCharged";
		Decal "Scorch";
	}
	
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC A 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(16,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC B 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC C 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(16,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC D 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC E 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(16,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC F 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC G 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(16,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC H 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC I 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(16,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC J 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC K 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(16,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC L 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC M 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        Stop;

      Death:
        TNT1 A 0;
        TNT1 A 0 A_Stop;
        TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 AAAAAAAAAAAAA 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",12,"Death12");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",11,"Death11");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",10,"Death10");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",9,"Death9");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",8,"Death8");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",7,"Death7");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",6,"Death6");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",5,"Death5");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",4,"Death4");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",3,"Death3");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",2,"Death2");
        TNT1 A 0 A_JumpIfInventory("PlasmaBeamCount",1,"Death1");

      Death1:
        LSMC A 1 BRIGHT;

      Death2:
        LSMC B 1 BRIGHT;

      Death3:
        LSMC C 1 BRIGHT;

      Death4:
        LSMC D 1 BRIGHT;

      Death5:
        LSMC E 1 BRIGHT;

      Death6:
        LSMC F 1 BRIGHT;

      Death7:
        LSMC G 1 BRIGHT;

      Death8:
        LSMC H 1 BRIGHT;

      Death9:
        LSMC I 1 BRIGHT;

      Death10:
        LSMC J 1 BRIGHT;

      Death11:
        LSMC K 1 BRIGHT;

      Death12:
        LSMC L 1 BRIGHT;

      Death13:
        LSMC M 1 BRIGHT;
        Stop;
    }
}

Class PlasmaBoltChargedCoop : PlasmaBoltCharged
{
	Default
	{
		+FORCEXYBILLBOARD;
		Damage (30);
		Speed 55;
		Scale 0.5;
	}
	
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC A 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC B 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC C 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC D 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC E 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC F 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC G 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC H 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC I 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC J 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC K 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC L 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        TNT1 A 0 A_GiveInventory("PlasmaBeamCount",1);
        TNT1 A 0 A_Explode(24,64,0);
        TNT1 AAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        TNT1 A 0 A_SpawnProjectile("PlasmaSmoke",0,0,Random(-200,200),3,Random(-200,200));
        LSMC M 1 BRIGHT A_SpawnItemEx("PlasmaTrailCharged",0,0,0,0,0,0,0,160);
        Stop;
    }
}

Class PlasmaTrailCharged : Actor
{
	Default
	{
		Alpha 0.45;
		Scale 0.5;
		+NOINTERACTION;
		+CLIENTSIDEONLY;
		+FORCEXYBILLBOARD;
		RenderStyle "Add";
	}
	
    States
    {
      Spawn:
        TNT1 A 0;
        TNT1 A 0 A_JumpIf(ACS_ExecuteWithResult(594,0,0,0) == 1,"Nope");
        TNT1 AAAAAA 0 A_SpawnItemEx("PlasmaSpark",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,400)/100.00,random(-180,180),160,0);
        LSMS ABCDEFGHIJKL 1 BRIGHT A_SpawnItemEx("PlasmaTrailFlicker",0,0,0,random(-200,200)/100.00,random(-200,200)/100.00,random(-200,200)/100.00,random(-180,180),160,0);
        Stop;

      Nope:
        TNT1 A 1;
        Stop;
    }
}

//Half Shot Actors
Class PlasmaBoltHalfCharged : PlasmaBoltCharged
{
	Default
	{
		+FORCEXYBILLBOARD;
		Radius 8;
		Height 6;
		Alpha 0.15;
		Damage (16);
		Scale 0.01;
	}
}

Class PlasmaTrailHalfCharged : PlasmaTrailCharged
{
	Default
	{
		+FORCEXYBILLBOARD;
		Alpha 0.15;
		Scale 0.01;
	}
}

//Half Shot Actors
Class PlasmaBoltHalfChargedCoop : PlasmaBoltChargedCoop
{
	Default
	{
		+FORCEXYBILLBOARD;
		Radius 8;
		Height 6;
		Alpha 0.15;
		Damage (16);
		Scale 0.01;
	}
}

//End of Half Shot Actors